name: gmaps_places_api_wrapper
description: A simple wrapper that simplifies dealing with Google Maps' places API for dart 
version: 1.0.0

environment:
  sdk: ">=2.10.5 <3.0.0"

dev_dependencies:
  build_runner: ^1.11.1
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  enum_to_string: ^1.0.14
  equatable: ^1.2.6
  http: ^0.12.2
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
