name: places_api_wrapper
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.5 <3.0.0"

#dependencies:
#  path: ^1.7.0
dev_dependencies:
  build_runner: ^1.11.1
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  enum_to_string: ^1.0.14
  equatable: ^1.2.6
  http: ^0.12.2
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  mockito: ^4.1.4
