name: gmaps_places_api_wrapper
description: A simple wrapper that simplifies dealing with Google Maps' places API for dart 
version: 2.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  build_runner: ^1.11.1
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  enum_to_string: ^1.0.14
  equatable: ^2.0.0-nullsafety.3
  http: ^0.13.0
  json_annotation: ^4.0.0
  json_serializable: ^4.0.1
